import type { Metadata } from "next";
import {
  Barlow,
  Merriweather,
  JetBrains_Mono,
  Outfit,
  Geist_Mono,
} from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { PublicConfigProvider } from "@/context/PublicConfigContext";
import { ModalProvider } from "@/context/ModalContext";
import { TooltipProvider } from "@/components/ui/tooltip";

/* =====================================================
   Fonts
===================================================== */
const fontSans = Outfit({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["300", "400", "500", "600", "700"],
});

const fontSerif = Merriweather({
  subsets: ["latin"],
  variable: "--font-serif",
  weight: ["300", "400", "700", "900"],
});

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

/* =====================================================
   Metadata
===================================================== */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* =====================================================
   Layout
===================================================== */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}
      >
        <AuthProvider>
          <PublicConfigProvider>
            <TooltipProvider>
              <ModalProvider>{children}</ModalProvider>
            </TooltipProvider>
          </PublicConfigProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
